@startuml
actor Клиент
actor ЗарегКлиент
left to right direction

rectangle Cистема {
    ЗарегКлиент --|> Клиент
    Клиент "1..*" --- "*" (Работать с модулем\n безопасности)
    Клиент "1..*" --- "*" (Работать в личном\n кабинете)

    (Работать в личном\n кабинете) .> (Работать со счетами) : include
    (Работать в личном\n кабинете) -.> (Просматривать историю операций) : include

    (Работать с модулем\n безопасности) <.- (Выполнять вход) : extends
    (Работать с модулем\n безопасности) <.-  (Выполнять выход) : extends
    (Работать с модулем\n безопасности) <.  (Регистрироваться в системе) : extends
}
@enduml