@startuml
state "Ожидание запроса авторизации клиента" as s1
    s1: entry/ отобразить меню авторизации

state "Ввод данных" as s2
    s2: логин/ получить логин
    s2: пароль/ получить пароль
    s2: exit/ обращение к таблице клиентов в БД

state "Вывод" as s3
    s3: exit/ вернуться на главную страницу

[*] --> s1
s1 ---> s2
s2 --> s1 : неверный логин или пароль
s2 --> s3 : верный логин и пароль
s3 --> [*]

@enduml