@startuml
state "Ожидание запроса страницы\nличного кабинета" as s1
    s1: entry/ отобразить главное меню

state "Отображение личного кабинета" as s2{

    state "Отображение данных о пользователе" as s21
        s21: логин/ получить логин текущего пользователя
        s21: do/ найти данные пользователя в БД по логину
        s21: exit/ отобразить данные пользователя

    state "Отобразить список счетов" as s22
        s22 : do/ достать следующий счет из БД
        s22 : exit/ отобразить список счетов

    state "Отобразить данные истории операций" as s23
        s23 : do/ достать следующую операцию из БД
        s23 : exit/ отобразить страницу личного кабинета

    [*] --> s21
    s21 --> s22 : найти счета по id клиента
    s22 --> s22 : следующий счет
    s22 --> s23 : найти операции по счетам клиента
    s23 --> s23 : следующая операция
}

[*] --> s1
s1 --> s2 : выбор пункта меню\n"личный кабинет"
s2 --> [*]


@enduml