@startuml
state "Ожидание запроса страницы\nвнесения денег" as s1
    s1: entry/ отобразить главное меню

state "Ввод данных" as s2
    s2: сумма/ получить сумму
    s2: № счета/ получить номер счета

state "Проведение транзакции" as s3{
    state "Проверка данных" as s31
        s31: сумма/ сумма больше ноля
        s31: № счета/ счет с указанным номером существует
    state "Обновление БД" as s32
        s32: do/ обновление таблицы счетов
        s32: do/ новая запись в таблице операций
        s32: do/ новая запись таблице логов
        s32: exit/ вывод страницы успеха
    state "Вывод" as s33
        s33: do/ вывод страницы ошибки

    [*] --> s31
    s31 --> s32 : параметры\n удовлетворительны
    s31 -right-> s33 : параметры\nне удовлетворительны
}

[*] -> s1
s1 --> s2 : Выбор пункта меню\n"Внести деньги"
s2 --> s3 : Формирование транзакции
s3 --> [*]

@enduml