@startuml
state "Ожидание запроса страницы\nрегистрации клиента" as s1
    s1: entry/ отобразить меню авторизации

state "Ввод данных" as s2
    s2: логин/ получить логин
    s2: пароль/ получить пароль
    s2: E-mail/ получить E-mail
    s2: Имя/ получить Имя
    s2: Фамилия/ получить Фамилия
    s2: Отчество/ получить Отчество

state "Работа с БД" as s3 {
    state "Вывод" as error
        error: do/ вывод страницы ошибки
    state "Проверка логина" as s31
        s31: логин/ проверка на наличие такого логина в системе
    state "Проверка E-mail" as s32
        s32: E-mail/ проверка на наличие такого E-mail в системе
    state "Транзакция в БД" as s33
        s33: do/ создание записи в таблице пользователей, сохранение id клиента
        s33: do/ создание записи в таблице счетов по id клиента, сохранение id счета
        s33: do/ создание записи в таблице операций по id счета
        s33: do/ создание записи в таблице логов с указанием id клиента и операции
    state "Вывод успеха" as s34
        s34: exit/ вывести страницу успешной регистрации

    [*] --> s31
    s31 -> error : указанный логин существует
    s31 --> s32 : указанный логин не существует
    s32 -> error : указанный E-mail существует
    s32 --> s33 : указанный E-mail не существует
    s33 --> s34 : транзакция успешно прошла
}

[*] --> s1
s1 --> s2 : Выбор пункта меню\n"Регистрация"
s2 --> s3 : Обращение в БД
s3 --> [*]

@enduml