@startuml
(*)  --> "заходит на страницу банка"
if "зарегистрирован" then
    ---> [Да] "выполняет вход"
    ---> "входит в личный кабинет,\n видит баланс лицевого счета"
else
    ---> [Нет] if "хочет зарегистрироваться"
        --> [Да] "регистрируется"
        --> "входит в личный кабинет,\n видит баланс лицевого счета"
        --> if "хочет выполнить действие со счетом" then
                --> [Да] ===REDIRECT_CHECK===
            else
                --> [Нет] "выходит из личного кабинета"
                --> "закрывает страницу банка"
            endif
        else
    else
        --> [Нет] "закрывает страницу банка"
endif
===REDIRECT_CHECK=== --> "пополняет счет"
===REDIRECT_CHECK=== --> "переводит деньги\n другому клиенту"
===REDIRECT_CHECK=== --> "выводит средства\nсо счета"

"пополняет счет" ---> ===PARALLEL_END===
"переводит деньги\n другому клиенту" ---> ===PARALLEL_END===
"выводит средства\nсо счета" ---> ===PARALLEL_END===
--> if "хочет выполнить еще одно действие" then
        --> [Да] "входит в личный кабинет,\n видит баланс лицевого счета"
    else
        --> [Нет] "выходит из личного кабинета"
    endif

"закрывает страницу банка" -->(*)
@enduml