@startuml



node "Server"{

    package "docker containers"{
        artifact "Main application" as ma
        artifact "Security application" as sa
        artifact "Account application" as aa
        artifact "DataAccess application" as da
        database "MySQL Database" as db
        ma -- sa
        ma -- aa
        sa -- da
        aa -- da
        da -- db
    }
}

node "Client's device"{
    [Browser]
}

[Browser] -- ma
@enduml