@startuml

actor Клиент
actor ЗарегКлиент
left to right direction

rectangle Cистема {
    Клиент <|-- ЗарегКлиент
    ЗарегКлиент "1..*" -- "*" (Работать в личном\n кабинете)

    (Работать в личном\n кабинете) .> (Работать со счетами) : include

    (Работать со счетами) .> (Пополнять счет) : include
    (Работать со счетами) -.> (Выводить средства\nсо счета) : include
    (Работать со счетами) -.> (Выполнять перевод) : include
    (Выполнять перевод) <. (Принять перевод\n от клиента банка) : extend
    (Перевести деньги\n клиенту банка) .> (Выполнять перевод) : extend

    (Просматривать историю\nопераций) <. (Работать в личном\n кабинете) : include


    note "Источник/приемник денег - банкомат\nбанка или счет мобильного телефона" as N2
    (Пополнять счет) . N2
    N2 . (Выводить средства\nсо счета)
}
@enduml