@startuml
:Модуль безопасности: as n1
actor Клиент
actor ЗарегКлиент
left to right direction

rectangle n1 {
    Клиент "1..*" ---- "*" (Регистрироваться в системе)
    ЗарегКлиент "1..*" ---- "*" (Выполнять вход\nв личный кабинет)
    ЗарегКлиент "1..*" ----"*" (Выполнять выход\nиз личного кабинета)

    (Выполнять вход\nв личный кабинет) -.> (Работать с модулем\n безопасности) : extend
    (Выполнять вход\nв личный кабинет) .> (Указать логин и пароль) : include

    (Выполнять выход\nиз личного кабинета) -.> (Работать с модулем\n безопасности) : extend
    (Регистрироваться в системе) -.> (Работать с модулем\n безопасности) : extend
    (Регистрироваться в системе) -.> (Указать логин, пароль, ФИО) : include

    note top of (Указать логин, пароль, ФИО) : В результате клиент становится \nзарегистрированным клиентом
    note top of (Выполнять выход\nиз личного кабинета) : Если выполнен вход в личный кабинет
    note bottom of (Выполнять вход\nв личный кабинет) : Если не выполнен вход в личный кабинет
}
@enduml